// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"teamspeak-one-click-deploy/internal/dao/internal"
)

// loginAuditDao is the data access object for the table login_audit.
// You can define custom methods on it to extend its functionality as needed.
type loginAuditDao struct {
	*internal.LoginAuditDao
}

var (
	// LoginAudit is a globally accessible object for table login_audit operations.
	LoginAudit = loginAuditDao{internal.NewLoginAuditDao()}
)

// Add your custom methods and functionality below.
