// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"teamspeak-one-click-deploy/internal/dao/internal"
)

// oauthAccountsDao is the data access object for the table oauth_accounts.
// You can define custom methods on it to extend its functionality as needed.
type oauthAccountsDao struct {
	*internal.OauthAccountsDao
}

var (
	// OauthAccounts is a globally accessible object for table oauth_accounts operations.
	OauthAccounts = oauthAccountsDao{internal.NewOauthAccountsDao()}
)

// Add your custom methods and functionality below.
