// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"teamspeak-one-click-deploy/internal/dao/internal"
)

// usersAuthDao is the data access object for the table users_auth.
// You can define custom methods on it to extend its functionality as needed.
type usersAuthDao struct {
	*internal.UsersAuthDao
}

var (
	// UsersAuth is a globally accessible object for table users_auth operations.
	UsersAuth = usersAuthDao{internal.NewUsersAuthDao()}
)

// Add your custom methods and functionality below.
