// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"teamspeak-one-click-deploy/internal/dao/internal"
)

// verificationTokensDao is the data access object for the table verification_tokens.
// You can define custom methods on it to extend its functionality as needed.
type verificationTokensDao struct {
	*internal.VerificationTokensDao
}

var (
	// VerificationTokens is a globally accessible object for table verification_tokens operations.
	VerificationTokens = verificationTokensDao{internal.NewVerificationTokensDao()}
)

// Add your custom methods and functionality below.
